server:
  port: 10003
spring:
  application:
    name: JA-STAFF
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.3.138:3333/ja_erp?zeroDateTimeBehavior=convertToNull&useUnicode=TRUE&characterEncoding=utf8&autoReconnect=true
    username: root
    password: 123456
  redis:
    host: 192.168.3.138
    port: 6379
    database: 0
    jedis:
      pool:
        max-active: 8
        max-idle: 8
        max-wait: -1
        min-idle: 0
  activemq:
    broker-url: tcp://192.168.3.138:61616
    user: admin
    password: admin
    pool:
      enabled: true
      max-connections: 50
  messages:
    basename: i18n/messages
  cloud:
    loadbalancer:
      retry:
        enabled: true
mybatis:
  type-aliases-package: com.champlink.common.domain.staff
  mapper-locations: classpath*:com/champlink/staff/mapper/**/*Mapper.xml
  configuration:
    map-underscore-to-camel-case: true
logging:
  level:
    com.champlink.staff.dao: DEBUG
pagehelper:
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true
  params: count=countSql
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 10000
JA-STAFF: 
  ribbon:
    ConnectTimeout: 500
    ReadTimeout: 1000
    OkToRetryOnAllOperations: true
    MaxAutoRetriesNextServer: 2
    MaxAutoRetries: 3