server:
  port: 10006
spring:
  datasource:
    url: jdbc:mysql://172.16.8.78:3306/ja_erp?zeroDateTimeBehavior=convertToNull&useUnicode=TRUE&characterEncoding=utf8&autoReconnect=true
    username: root
    password: 123456
    hikari:
      maximum-pool-size: 1
  redis:
    host: 172.16.8.78
    port: 6379
    password: ja@redis
  activemq:
    broker-url: tcp://172.16.8.78:61616
    user: admin
    password: admin
fdfs:
  trackServer: 172.16.8.71:22122
  connectTimeoutInSeconds: 10
  networkTimeoutInSeconds: 30
  charset: UTF-8
  httpTrackerHttpPort: 80