server:
  port: 10006
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/ja_erp?zeroDateTimeBehavior=convertToNull&useUnicode=TRUE&characterEncoding=utf8&autoReconnect=true
    username: root
    password: 123456
    hikari:
      maximum-pool-size: 1
  redis:
    host: localhost
    port: 6379
fdfs:
  trackServer: 172.28.9.43:22122
  connectTimeoutInSeconds: 10
  networkTimeoutInSeconds: 30
  charset: UTF-8
  httpTrackerHttpPort: 80