server:
  port: 20001
spring:
  datasource:
    url: jdbc:mysql://172.28.9.43:3306/ja_erp?zeroDateTimeBehavior=convertToNull&useUnicode=TRUE&characterEncoding=utf8&autoReconnect=true
    username: jingao
    password: jingao@erp
    hikari:
      maximum-pool-size: 1
  redis:
    host: 172.28.9.43
    port: 6379
  activemq:
    broker-url: tcp://172.28.9.43:61616
    user: admin
    password: admin