server:
  port: 30005
spring:
  datasource:
    url: jdbc:mysql://172.28.9.18:3306/ja_erp?zeroDateTimeBehavior=convertToNull&useUnicode=TRUE&characterEncoding=utf8&autoReconnect=true
    username: ja
    password: qp9meUJN48NcXk5y
    hikari:
      maximum-pool-size: 1
  redis:
    host: 172.28.9.25
    port: 6379
    password: ja_erp@2018
  activemq:
    broker-url: tcp://172.28.9.25:61616
    user: admin
    password: admin
fdfs:
  trackServer: 172.28.9.19:22122
  connectTimeoutInSeconds: 10
  networkTimeoutInSeconds: 30
  charset: UTF-8
  httpTrackerHttpPort: 80