server:
  port: 30005
spring:
  datasource:
    url: jdbc:mysql://172.29.15.43:3306/ja_erp?zeroDateTimeBehavior=convertToNull&useUnicode=TRUE&characterEncoding=utf8&autoReconnect=true
    username: jingao
    password: jingao@erp
  redis:
    host: 172.29.15.43
    port: 6379
  activemq:
    broker-url: tcp://172.29.15.43:61616
    user: admin
    password: admin