server:
  port: 10007
spring:
  datasource:
    url: jdbc:mysql://192.168.3.138:3333/ja_erp?zeroDateTimeBehavior=convertToNull&useUnicode=TRUE&characterEncoding=utf8&autoReconnect=true
    username: root
    password: 123456
  redis:
    host: 192.168.3.138
    port: 6379
  activemq:
    broker-url: tcp://192.168.3.138:61616
    user: admin
    password: admin