server:
  port: 10003
spring:
  datasource:
    url: jdbc:mysql://172.29.15.42:3306/ja_erp?zeroDateTimeBehavior=convertToNull&useUnicode=TRUE&characterEncoding=utf8&autoReconnect=true
    username: ja
    password: ja@2018
    hikari:
      maximum-pool-size: 1
  redis:
    host: 172.29.15.42
    port: 6379
    password: ja@redis
  activemq:
    broker-url: tcp://172.29.15.42:61616
    user: admin
    password: admin