server:
  port: 9999
spring:
  application:
    name: JA-DISCOVERY
eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: http://${server.host:localhost}:${server.port:9999}/eureka